### ISSUE TITLE
eGPU Thunderbolt 3 Issue

### ISSUE THREAD

**Issue by iNuc-Pro** [basett1/INTEL_NUC10i5FNH#2]
Hi Basett, Good job compiling the working EFI. I've read the previous model Nuc8iBEH in tonymac and eGPU.io forums that the only way to enable TB3 for eGPU is to flash the firmware, using the https://github.com/osy/ThunderboltPatcher. Maybe you should try?

**Comment by iNuc-Pro** [comment]
this one can get the eGPU running without flashing https://github.com/sarkrui/NUC8i7BEH-Hackintosh-Build

**Comment by basett1** [comment]
Hi, sorry for late reply.. pls try the new efi
